### ISSUE TITLE
Build facil.io into an DLL?

### ISSUE THREAD

**Issue by altPOCA** [boazsegev/facil.io#131]
I know facil.io is originally a C only library but being in C it could be easy used in other language, too. The problem is the the way your software is developed requires it to be used with C only as there is no DLL to work with and one has to work in source form. Could you change it to add the ability to build facil.io into an DLL? This could have other language doesn't have a web framework now could have a web framework. For example: FreeBASIC.

Thanks.

**Comment by boazsegev** [comment]
Hi @altPOCA ,

Thank you for your interest in facil.io and in the idea of exposing its API to FreeBASIC.

Although @janbiedermann is doing amazing work porting a working version of facil.io to Windows (see PR #106 ), compiling a DLL is not enough. Much work is required in order to expose the API in a way that is FreeBASIC compatible and friendly (and preferably in a way that allows user to use the API in an idiomatic way to the language.

This might be less or more than the work required to write [`iodine` (the gem that publishes the facil.io API to Ruby)](https://github.com/boazsegev/iodine), since `iodine` also includes a default facil.io implementation (HTTP / WebSocket server with pub/sub and support for Redis)... but it will be a lot of work regardless and it requires someone experienced with FreeBASIC (which, I'm not).

I'd be happy to see such a project through, but I do warn you that I hope to release version 0.8.x in the not too far future and that I expect major API breaking changes (there are some core design changes in the latest draft).

If you plan to start a project that will compile facil.io as a DLL (this might require a few minor changes to the `makefile` and could be implemented on windows using an MSVC project file) and publish the API to FreeBASIC, I will try to throw support your way... but... this being a negatively paying job where time and money are concerned (it's all take and no give), I don't make any promises regarding how fast or often I can work.

Anyway, Good Luck!!!

Thanks again for your interest,
B.

**Comment by altPOCA** [comment]
FreeBASIC is available on Linux, too. I should rephrase my issue from building into DLL to building into shared library to be more clear. The only thing you should do is make it able to build facil.io into a shared library, the FreeBASIC binding or any language's binding is up to their respective community.

**Comment by boazsegev** [comment]
Do you mean something like [`make lib`](https://github.com/boazsegev/facil.io/blob/master/makefile#L696) (should work...) or `make install` (currently make will not automatically install the compiled library files)...?

**Comment by altPOCA** [comment]
> Do you mean something like [`make lib`](https://github.com/boazsegev/facil.io/blob/master/makefile#L696) (should work...) or `make install` (currently make will not automatically install the compiled library files)...?

Yes. I don't know it's already possible.
