### ISSUE TITLE
Potential concurrency issue? Wrong file names on some requests.

### ISSUE THREAD

**Issue by dertuxmalwieder** [boazsegev/facil.io#140]
I have - more or less - successfully ported one of my PHP websites to facil.io now (and I adore the performance). Still, I want to have a *special* handling of some certain paths, e.g. `/_versioninfo.txt` which I want to load from a local directory.

Here are the relevant parts of my code (I used the default skeleton, so the `initialize_http_service` part is kept original):

```c
static void on_http_request(http_s *h) {
  /* Wrap the requested path into a string so we can process it easier: */
  fio_str_info_s path_str = fiobj_obj2cstr(h->path);

  /* Clean the path variable: */
  char* path_str_clean = path_str.data;
  path_str_clean = remove_double_slashes(path_str_clean);

  /* Check for special files: */
  if (strcmp(path_str_clean, "/_versioninfo.txt") == 0) {
    // ... here's a call to http_send_body() */
  }

  // ...
}
```

Now the problem is that this works unreliably. Trying to open `localhost/_versioninfo.txt` leads to `path_str_clean` not always being `/_versioninfo.txt`. Printing the variable yields `/txersioninfo.txt` *sometimes* (every third time or so).

`remove_double_slashes` is a no-op right now while I debug this:

```c
char* remove_double_slashes(char* str) {
    return str;
}
```

Do you happen to have a clue what's going on?

**Comment by boazsegev** [comment]
I cannot test for a bug without example code that introduces the issue. However...

This sounds like a possible double free issue, where you are freeing a FIOBJ object more than once.

This will cause the custom allocator to mark used memory as available and possibly to allocate the same memory to a new variable (causing 2 variables to use the same memory).

Note that all the `FIOBJ` objects in the HTTP handle are owned by the handle. If you place them into an array or a Hash, you will need to call `fiobj_dup` in order to acquire another reference.

P.S.

Why not [setup a `public_folder` in the `http_listen` settings](https://github.com/boazsegev/facil.io/blob/7b8e5fcf5e945d07df92aca7728909c5887a80fc/lib/facil/http/http.h#L333-L343) and place that file in the public folder?

Alternatively, consider using the [`http_sendfile2` function](http://facil.io/0.7.x/http#http_sendfile2) to send a file from a public folder. If the function fails you can still handle the HTTP request manually ([this is what the `public_folder` setting does](https://github.com/boazsegev/facil.io/blob/7b8e5fcf5e945d07df92aca7728909c5887a80fc/lib/facil/http/http_internal.c#L45-L52))...

Since the code already exists (including protection against tree transversal), it could make life easier for you.

**Comment by dertuxmalwieder** [comment]
I actually use `http_sendfile2` for this. :-)
I free all FIOBJs at the end of the `on_http_request` method, after using any of them. No arrays, no hashes. Are there any other methods that modify them internally?

**Comment by boazsegev** [comment]
> I free all `FIOBJ`s at the end of the on_http_request method

I hope you meant to write that you free all the **temporary** `FIOBJ` objects that you yourself created.

Remember that all the `FIOBJ` objects that come from the HTTP handle are managed by the facil.io framework and should **NOT** be freed.

For example:

* `h->path` must **NOT** be freed.
* Any header **value** set using [`http_set_header`](http://facil.io/0.7.x/http#http_set_header) should **NOT** be freed (you moved the memory ownership to the HTTP handle) (header names, unless cached, **should** be freed as their ownership remains with you).
* Any `FIOBJ` header / cookie value collected from the `h->headers` or `h->cookies` hash is still owned by the hash and must **NOT** be freed.

Unless I could reproduce the issue or see some example code, I won't be able to debug the issue... but I hope this helps.

Happy New Year!

**Comment by dertuxmalwieder** [comment]
> I hope you meant to write that you free all the temporary `FIOBJ` objects that you yourself created.

Yes, sure. Sorry for the confusion. :-) 

I think I found the problem. It was, not surprisingly, in my own code. For those having similar issues later, I even quoted the bad part in my initial comment:

```c
char* path_str_clean = path_str.data;
```

Modifying facil.io-supplied strings from a copy created *this* way will most likely break somewhere in the code. Fix:

```c
char* path_str_clean = strdup(path_str.data);
```

I should probably stop writing issues here. Most of them show a lack of basic understanding on my side. 🙄
Happy new year to you as well! I promise: I'll do better in the future.
