### ISSUE TITLE
Error: unknown field ‘buffer’ specified in initializer

### ISSUE THREAD

**Issue by raminfp** [boazsegev/facil.io#15]
Hi @boazsegev ,

you define method [sock_write2](https://github.com/boazsegev/facil.io/blob/master/lib/facil/core/sock.h#L353&L354) and .buffer must accept `int` [ `The buffer contains the value of a file descriptor (`int`)`](https://github.com/boazsegev/facil.io/blob/master/lib/facil/core/sock.h#L288)

Issue :

[.buffer](https://github.com/boazsegev/facil.io/blob/master/lib/facil/core/facil.c#L916) when will compile code we got error message : `lib/facil/core/sock.h:353: error: unknown field ‘buffer’ specified in initializer` 
 
this error tells us that the initializer and the [struct ](https://github.com/boazsegev/facil.io/blob/master/lib/facil/core/facil.c#L883)are using different types, different field names, and different number of elements. 

Thanks,

**Comment by boazsegev** [comment]
Hi @raminfp ,

Thank you for opening this issue.

Could you attach a short example code that produces the compilation error (no need for a valid program, just a line or two of code)...?

The reason I ask is this:

As you noticed, [`sock_write2`](https://github.com/boazsegev/facil.io/blob/4a6368d25e5501edda03a38e9f0bb4f7fbd81e71/lib/facil/core/sock.h#L327) is just a macro for the [`sock_write2_fn`](https://github.com/boazsegev/facil.io/blob/4a6368d25e5501edda03a38e9f0bb4f7fbd81e71/lib/facil/core/sock.h#L316-L319) which accepts a [`sock_write_info_s` struct](https://github.com/boazsegev/facil.io/blob/4a6368d25e5501edda03a38e9f0bb4f7fbd81e71/lib/facil/core/sock.h#L261-L311) as an argument.

The `.buffer` field is [defined within an anonymous union inside the `sock_write_info_s ` struct](https://github.com/boazsegev/facil.io/blob/4a6368d25e5501edda03a38e9f0bb4f7fbd81e71/lib/facil/core/sock.h#L264-L269) of `const intptr_t data_fd fd` (for file descriptors) and `const void *buffer` for in memory data, since both can't be used at once.

Because I'm using an anonymous union, this might be a compiler issue... or maybe something else is happening in the code. I want to test this out.

P.S.

I couldn't follow the links since they broke after I committed some changes...

In the future, please use the `y` key to get GitHub to provide you with a persistent link. These links can survive file changes by linking to a specific version.

Thank you!

**Comment by raminfp** [comment]
>Because I'm using an anonymous union, this might be a compiler issue.

maybe! i use gcc version :
```bash
[root@localhost core]# gcc --version
gcc (GCC) 4.4.7 20120313 (Red Hat 4.4.7-18)
Copyright (C) 2010 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
```

**Comment by boazsegev** [comment]
That's an old version... I think the oldest I tested against was `gcc` 4.8.4... I don't have an older copy to test with...

Can you test with a different compiler and see if this helps? ... just to make sure it's not something else...?

**Comment by raminfp** [comment]
@boazsegev Thanks work it with version gcc (GCC) 4.9.1 20140922,

sorry for open isseu,

**Comment by boazsegev** [comment]
@raminfp ,

I'm happy I could help. I guess it's also my fault for mentioning the project requires C11.

Besides, it's better that you open a hundred issues like this than `facil.io` having a real issue I don't know about 👍🏻

Thanks Again,
B.
