### ISSUE TITLE
I can use facil lib in http protocol response? 

### ISSUE THREAD

**Issue by raminfp** [boazsegev/facil.io#17]
Hi @boazsegev ,

I have question! how to i use facil lib in http protocol response for get status response `ex: (OK) 200,(forbidden) 404,...`,
i saw your http lib but sill i'm not sure, please help, 

my means : this is a an example of `CURLlib`, `CURLE_OK == 200` if it's status == 200 in response, you will see printf("OK\n"),

```C
#include <stdio.h>
#include <curl/curl.h>
 
int main(void)
{
  CURL *curl;
  CURLcode res;
 
  curl = curl_easy_init();
  if(curl) {
  
    curl_easy_setopt(curl, CURLOPT_URL, "http://google.com");
    res = curl_easy_perform(curl);
    if(res == CURLE_OK) {
        printf("OK!\n ");
        long response_code;
        curl_easy_getinfo(curl, CURLINFO_RESPONSE_CODE, &response_code);
    }
    curl_easy_cleanup(curl);
  }
  return 0;
}
```

Thanks,

**Comment by boazsegev** [comment]
Hi @raminfp ,

Facil.io doesn't have an HTTP *client* implementation right now, only Ann HTTP *server*.

By this, I mean that facil.io can create a response (i.e., set the states using response->status = 400)... but it doesn't parse a response.

It's easy to use the existing facil.io core to create a connection to a server. SSL/TLS is more complicated, but can be accomplished using the `sock_rw_hook_set`...

...but there isn't a **client** HTTP/1.x parser, which you will need to write (perhaps recycle some of the code from the existing HTTP **server**).

Also, `curl` offers redirection resolution and other features that you will need to handle.

`curl` should be usable within a `facil.io` project, preferably using the `curl_multi` interface (though you could use the `easy` interface and spawn new threads).

**Comment by raminfp** [comment]
Thanks a lot for you answer!

>...but there isn't a client HTTP/1.x parser, which you will need to write (perhaps recycle some of the code from the existing HTTP server).

Yes,sure,

>It's easy to use the existing facil.io core to create a connection to a server. SSL/TLS is more complicated, but can be accomplished using the sock_rw_hook_set...

True, still i not more familiar `facil.io`,so i am working in your libs this week, :)

**Comment by boazsegev** [comment]
Hi @raminfp ,

I'm just dropping a note to point out that I refactored the HTTP parser to include a possible `client` mode (it's in the `master` development branch).

Unless you're implementing a server, you would probably move on to the next library, but I thought you might like to know. After all, it was your question that inspired me to rewrite the parser and add client mode support.

I hope in the future the library will have an HTTP client as well, but for now it's just a small hope.

Kindly,
  B.

**Comment by neel** [comment]
HTTP client support is required for me as well.

**Comment by boazsegev** [comment]
Hi @neel ,

Thanks for the vote. I'm actually experimenting with rewriting the HTTP extension and I'm happy to read feedback while I'm pushing possible changes to the [ReHTTP branch](https://github.com/boazsegev/facil.io/tree/reHTTP).

Along this process I'm trying to author an HTTP client and decouple the HTTP request/response (re)design from the network IO layer (which will solve some issues I had trying to implement HTTP/2).

Anyway, now is definitely a good time to point out anything you would like to see improved :-)

**Comment by neel** [comment]
I have written a tiny http router (though I’vent started working with it) I would be glad to share it.

**Comment by boazsegev** [comment]
Sounds interesting. Does it support AJAX? Can I have a look?

**Comment by neel** [comment]
I don't know what special has to be done for AJAX in server side unless there is a requirement of long polling. So far this is just an urlpatterns like python django, however uses POSIX regex instead of PCRE. This is tiny. Added router.h and router.c in the zip.

Example usercode will look like this

 ```
url_pattern_s urlpatterns[] = {
    {.method = "GET" , .pattern = "/connections",                  .callback = http_action},
    {.method = "GET" , .pattern = "/connection/([a-zA-Z0-9]+)/",   .callback = http_action},
    {.method = "POST", .pattern = "/acquire/([a-zA-Z0-9]+)/",      .callback = http_action},
    {.method = "POST", .pattern = "/release/([a-zA-Z0-9]+)/",      .callback = http_action},
    {.method = "GET" , .pattern = "/health",                       .callback = http_action}
 };
 route(request, urlpatterns, sizeof(urlpatterns)/sizeof(url_pattern_s));
```

router.h
```
typedef struct url_captures{
    short   count;
    char**  matches;
} url_captures_s;

typedef int (*url_callback_t)(http_request_s*, url_captures_s*);

typedef struct url_pattern{
    const char* method;
    const char* pattern;
    url_callback_t callback;
} url_pattern_s;

void caps_free(url_captures_s* capture);
int callback_wrapper(http_request_s* request, url_captures_s* captures, url_callback_t callback);
int regex_match(const char* pattern, const char* subject, url_captures_s** captures);
int route(http_request_s* request, url_pattern_s* routes, int len);
```
router.c
```
void caps_free(url_captures_s* capture){
    char** matches = capture->matches;
    do{
        free(*matches);
        *matches = 0x0;
    }while(*(++matches));
    free(capture->matches);
    free(capture);
}

int callback_wrapper(http_request_s* request, url_captures_s* captures, url_callback_t callback){
    int status = callback(request, captures);
    return status;
}

/**
 * user code should NOT create the url_captures_s object but MUST FREE it with `caps_free` once the out parameter captures is filled by the function
 */
int regex_match(const char* pattern, const char* subject, url_captures_s** captures){
    short       max = 8;
    regmatch_t  matches[max];
    
    url_captures_s* url_captured = (url_captures_s*)calloc(1, sizeof(url_captures_s));
    url_captured->count = 0;
    url_captured->matches = (char**)calloc(1, sizeof(char*));
    url_captured->matches[0] = '\0';
    
    regex_t regx;
    int status = regcomp(&regx, pattern, REG_EXTENDED);
    if(!status){
        status = regexec(&regx, subject, max, matches, 0);
        if(!status){
            short i = 0;
            for(;i < max; ++i){
                if(matches[i].rm_so < 0) break;
                regoff_t nchars = matches[i].rm_eo - matches[i].rm_so;
                char captured[64];
                memset(captured, 0, 64);
                strncpy(captured, subject+matches[i].rm_so, nchars);
                
                char* buffer = calloc(nchars+1, sizeof(char));
                strncpy(buffer, captured, nchars);
                url_captured->matches[url_captured->count] = buffer;
                url_captured->count++;
                url_captured->matches = realloc(url_captured->matches, url_captured->count*sizeof(char*));
                url_captured->matches[url_captured->count] = 0x0;
            }
        }
    }
    regfree(&regx);
    *captures = url_captured;
    return status;
}

int route(http_request_s* request, url_pattern_s* routes, int len){
    url_pattern_s* route = routes;
    while(len--){
        url_captures_s* captures = 0x0;
        if(!strcmp(route->method, request->method) && !regex_match(route->pattern, request->path, &captures)){
            callback_wrapper(request, captures, route->callback);
            break;
        }
        if(captures) caps_free(captures);
        route++;
    }
    return len;
}
```


[Archive.zip](https://github.com/boazsegev/facil.io/files/1586784/Archive.zip)

**Comment by boazsegev** [comment]
@neel ,  This looks really cool 👍 

However, I won't merge this approach to the current facil.io branch, since I'm avoiding RegEx while I can.

Also, I was hoping to have something reminiscent of node.js, where path names such as `"/users/(:id)"` allow you to match the path `/users` with the *optional* `id` parameter (as if the `id` was a query `/users?id=X`...

Anyway, still a lot to do, the HTTP/1.1 client is probably next on my list (I'm almost done re-designing the HTTP extension).

**Comment by neel** [comment]
I see. Thats a good approach, easier to use as well. But I needed a solution fast, so that was a 10 minutes solution. But I can still cheat :) by replacing `(:id)` with `([0-9]+)`.

Anyways I am curious why are you avoiding regex ? you could still use placeholders with PCRE regex. And many other frameworks use regex.

**Comment by boazsegev** [comment]
Hi @neel

> Anyways I am curious why are you avoiding regex ? you could still use placeholders with PCRE regex. And many other frameworks use regex.

I think regex is wonderful, it's just that my experience shows that it's not the best tool for routing.

It's great for small collections, but it performs poorly where a larger number of routes might be deployed.

Using regex for matching routes often results in a liner approach, where the worst case scenario is O(n+1) (where n is the number of routes). Multiplying this approach with the costs of regex testing can get expensive for larger routing maps.

Also, I find large routing maps get difficult to maintain. I wonder it it might make more sense to design the router as a tree, where each branch can be updated in it's own space (i.e., the `/users` branch might be specified in a different `.c` file than the `/posts` branch).

The fastest and clearest approach I found so far was [Jeremy Evans's approach in Roda](http://roda.jeremyevans.net), where a tree was used for routing.

> Also would you care to document the internal data structures ? like the hash table, list etc.. So that I can reuse them.

*Documentation is my nemesis, it seems (that and writing tests, are probably the two most important aspects I neglect in my hobby projects)*.

**Yes**, definitely - but it might take me a bit because I'm rewriting the core types along with the changes to the framework (the upcoming version 0.6.0).

Although the API for the `fiobj` (fail.io objects) remains largely stable, I'm moving the [dynamic array](https://github.com/boazsegev/facil.io/blob/6569e3c1f2575609c174c87429c2e975b7ee06fe/lib/facil/core/types/fiobj/fio_ary.h), the [linked list](https://github.com/boazsegev/facil.io/blob/6569e3c1f2575609c174c87429c2e975b7ee06fe/lib/facil/core/types/fiobj/fio_llist.h) and the [hash map](https://github.com/boazsegev/facil.io/blob/6569e3c1f2575609c174c87429c2e975b7ee06fe/lib/facil/core/types/fiobj/fio_hashmap.h) logic to small single-file libraries (I might rename the list file after I remove the old version).

I think the documentation in the code is fairly clear, but I know how annoying it gets to read documentation in code comments. I'll add as much to the website as I can (help would be appreciated).
