### ISSUE TITLE
Add feature MD5 

### ISSUE THREAD

**Issue by raminfp** [boazsegev/facil.io#20]
Hi @boazsegev ,

do you have plan for add md5 to bscrypt?

[MD5 source code](https://gist.github.com/creationix/4710780)

Best Regards,

**Comment by boazsegev** [comment]
Hi @raminfp ,

Thanks for opening this issue.

Can you show any use-case for MD5?

I didn't write an implementation because I didn't see any use for MD5. It's insecure and should be avoided. See also the comment in the link you referenced:

> **Warning**: MD5 is not considered secure anymore. For secure software, please use SHA-256 or SHA-512 instead.

I'll be happy to add an implementation if you can show me a use-case, but otherwise I think it's better to minimize access to insecure algorithms.

Bo.

**Comment by raminfp** [comment]
Thanks for answer,

Yeah,i use projects for insert to DB with convert plaintext password to md5,
so you means `MD5 is completely broken.`  is not secure, rigth? and your suggestion i use sha256 ?

**Comment by boazsegev** [comment]
Yes, MD5 is completely broken.

SHA1 is also broken (but it's used in Websocket validation, where security doesn't matter).

Use SHA2, preferably SHA-512/256 (in `bscrypt` it's the `SHA_512_256` variant).

You can also use SHA3, which is the latest member of the SHA family... I didn't write an implementation yet (I hope to get around to it, but there's so much to do and so little time).

Good Luck!

B.

**Comment by raminfp** [comment]
Ok, Thanks a lot, i use your lib it's very good,

**Comment by boazsegev** [comment]
I'm happy you're enjoying the library ☺️👍🏻
