### ISSUE TITLE
Compiler error on chnage read-only variable t

### ISSUE THREAD

**Issue by vit1251** [boazsegev/facil.io#21]
https://github.com/boazsegev/facil.io/blob/8ba77c66f6019e6b35c9b1ea680d2b69bf473837/lib/facil/core/types/fiobj/fiobj_json.c#L102

**Comment by boazsegev** [comment]
Hi @vit1251 ,

Thank you for opening this issue.

I don't get this error. Could you show me a short example where the compiler emits this error?

Kindly,
   Bo.

**Comment by boazsegev** [comment]
Also, which compiler are you using?

**Comment by boazsegev** [comment]
@vit1251 ,

I can recreate the issue with gcc version 4.8.4 and 5.4.0... but not on clang.

`t` isn't defined as a const, but the struct itself contains `const` variables.

I'm not sure if this is a compiler issue or if clang is being lax, but I fixed this by removing the `const` keywords in `fiobject.h`, so that `fio_cstr_s` will be defined without any `const` fields.

Thank you very much for opening the issue.

Kindly,
   Bo.

**Comment by boazsegev** [comment]
@vit1251 ,

Thank you again for inspiring me to test the code under different compiler versions.

I tested it against `gcc` versions 5 & 6 as well as `clang` and committed some compatibility updates for the upcoming 0.5.5 version.

B.
