### ISSUE TITLE
Is building on Windows supported?

### ISSUE THREAD

**Issue by nullivex** [boazsegev/facil.io#28]
Hi,

I am currently looking into using this framework on an upcoming project I am trying to finish. I thought that this was a good lighter alternative for a TCP implementation than LibUV.

I am curious about building on Windows. I was able to use `cmake` with no erroneous output however I also dont see any binaries or headers.

The `makefile` doesnt seem to support Windows. Am I just way off the beaten path here?

**Comment by boazsegev** [comment]
Hi @nullivex ,

Thank you for your interest in facil.io.

You're welcome to pick the framework apart for parts... but at the moment, Windows support isn't implemented (I'm not sure I'll ever get there, as I have no platform on which to test Windows builds).

To support Windows, there's a some required code updates which are:

1. Adding Windows support for the `evio` (evented IO) library by wrapping the Windows IO API.
2. Adding Windows support for the `sock` library by wrapping the Windows Socket API.
3. Adding Windows support for the `defer` library by adding the Windows Thread API to the thread creation / joining callbacks.
4. Adding Windows alternatives for POSIX datatypes and assumptions (there aren't many, but there are some), such as wrapping the Windows TempFile API in the `fiobj_data` type (that currently wraps the POSIX file API).

The Windows "evented" IO design is the greatest of challenges. It's totally different than Linux/BSD/macOS, since it's based on "Completion" rather Tham "Readiness" (a signal is raised once an action finished rather than when an action is possible).

Although this has some advantages for sending data, it's quite difficult to handle when waiting for data and it makes it far harder to bridge the two approaches into a single framework (although I did redesign `evio` using a "one-shot" approach, so I could eventually bridge the two designs).

I wish I could help you, but most of the windows developers I know use Vagrant or some other VM container (I read [Microsoft now supports a Linux subsystem](https://docs.microsoft.com/en-us/windows/wsl/install-win10))... especially since most deployments end up running on a Linux/Unix kernel (i.e. AWS, Heroku. etc').

I wish I could help more than that... but the best I can offer is that you use facil.io for parts or opt for a different framework.

Kindly,
    B.

**Comment by boazsegev** [comment]
I'm closing this issue, but you're welcome to keep chatting on this thread if there's anything you think I could help with.

B.

**Comment by nullivex** [comment]
@boazsegev Hi, thank you for the quick response and the insight. I see the issues that are present I was curious mainly because I like to develop native on Windows and then deploy on to Linux. If that sounds weird, it's because it takes care of true cross OS testing on the way out the door. Its been working well in our development process.

I think for this scenario I will continue working with LibUV again thank you for the time.

**Comment by trumblejoe** [comment]
I'm sorry to dredge this up from the dead, but I think wepoll might be helpful.
https://github.com/piscisaureus/wepoll

Examples of polling socket readiness with IOCP.
https://lenholgate.com/blog/2024/06/socket-readiness-without-device-afd.html

Last note, I know you mentioned not having a windows system to test on, I recommend something like bosgame's minipcs. They are fast and cheap boxes for dev work.
https://www.amazon.com/BOSGAME-Ubuntu-Graphics-Computer-Preinstalled/dp/B0DNFNXXYN

**Comment by boazsegev** [comment]
Hi @trumblejoe ,

This is now a moot issue, as [the development version (0.8.x)](https://github.com/facil-io/cstl) works on Windows. See, for example the discussion here: https://github.com/boazsegev/facil.io/issues/164#issuecomment-3208546719
