### ISSUE TITLE
memory leak? + `__unused` clashes with system macro

### ISSUE THREAD

**Issue by recoilme** [boazsegev/facil.io#3]
Hello
I try run WEBSOCKET_SHOOTOUT demo with ab -n 1000000 -c 200 -k http://127.0.0.1:3000/
and memory increase on each itteration on 500kb or so on mac os sierra...

**Comment by recoilme** [comment]
in Echo example leak is mutch smaller (around 4k)
i make it like:
copy echo server example if demo.c
make build
make db
./demo\ run

may it be some debug mode?

**Comment by boazsegev** [comment]
Hi @recoilme,

Thank you for opening this issue. I'm starting to look into it.

Could you let me know what tools (and settings) do you use to observe the memory leak?

I tried testing with Xcode instruments but although Xcode couldn't find a leak, the memory used did crawl up to ~413KiB and stabilized on that, but I'm assuming the memory grows has to do with a number of built in memory pools that are initializing or used by facil.io (otherwise I'm not sure it would stabilize).

I'll try a longer test next, but I'd love to know how you found the leak.

When testing facil.io I expect a consistent ~2Mb "leak" from one of the memory pools (that wouldn't be a leak, as the memory is intentionally retained)... but the leak you describe sounds different.

P.S.

`demo run` is just a script I'm using to run the code from macOS's finder. It calls `make run` within the correct folder. If any `.c` files were updated, their objects will be rebuilt. You can edit `demo run` to call `make clean` before the `make run` and get a fresh execution each time.

The actual executable is in `tmp/demo`

I might rename `demo run` to `make run` if you think that will make more sense.

**Comment by boazsegev** [comment]
P.S.

I just finished running iterations for almost an hour. I couldn't find a leak.

The memory growth seemed to stabilize after a while, probably once all the memory pools were initialized.

...

I might be missing something... or my testing tools might be.

I'm waiting to read back from you about the way you tested for the leak, so I can repeat the same test.

**Comment by recoilme** [comment]
Hi,  sorry night here,  iwill reproduce tomorrow. I run server. Check mem with top command. As iIremember mem after start around 5mb as iIremember (strange it must be less then Mb) .run  ab -n 1000000 -c 200 -k http://127.0.0.1:3000/ and see what after test memory  + on 500kb and don't free after test stop. I repeat this test 5-7times and after each step memory grow and don't free. 

I try test with hello world example from Readme,  and similar (around 500kb grow each start) 

I try build echo server example,  and memory grow only on 4kb always. Looks like thread (or fork) not clean after finish. 
Sorry,  for my bad language (
I may test tomorrow on cent os 7 (11 or so hours from now) or please write me how iImay help you find problem

**Comment by boazsegev** [comment]
I think `top` is exposing an OS feature.

I think the OS `malloc` doesn't free all the memory. I think `malloc` implements a process-specific memory pool that is dependent on memory stress over time... I might be wrong, but I'm not sure the memory growth is from `facil.io`.

Please write me about your experience with CentOS (I tested the code with Ubuntu, not CentOS). I want to know if the memory growth is specific to macOS or if it's global.

I think that Xcode in macOS has issues when testing for memory leaks and `mmap`. I think it doesn't work. I wrote tests to test my code, but I might have missed something.

**Comment by recoilme** [comment]
Hi @boazsegev !
I have a problem with __unused declaration then build on centos 7(
Looks like it declared before. Error log:
```
make build
In file included from /usr/include/fcntl.h:68:0,
                 from src/libsock.c:14:
/usr/include/bits/stat.h:106:31: error: expected identifier or '(' before '[' token
     __syscall_slong_t __unused[3];
                               ^
/usr/include/bits/stat.h:164:31: error: expected identifier or '(' before '[' token
     __syscall_slong_t __unused[3];
                               ^
In file included from src/libsock.c:16:0:
/usr/include/netdb.h:589:15: error: expected identifier or '(' before '[' token
   int __unused[5];
               ^
src/libsock.c: In function 'reactor_on_close':
src/libsock.c:38:32: warning: unused parameter 'uuid' [-Wunused-parameter]
 void reactor_on_close(intptr_t uuid) {}
                                ^
src/libsock.c: In function 'reactor_remove':
src/libsock.c:40:29: warning: unused parameter 'uuid' [-Wunused-parameter]
 int reactor_remove(intptr_t uuid) { return -1; }
                             ^
src/libsock.c: In function 'sock_touch':
src/libsock.c:46:26: warning: unused parameter 'uuid' [-Wunused-parameter]
 void sock_touch(intptr_t uuid) {}
                          ^
src/libsock.c: In function 'async_run':
src/libsock.c:52:22: warning: unused parameter 'task' [-Wunused-parameter]
 int async_run(void (*task)(void *), void *arg) { return -1; }
                      ^
src/libsock.c:52:43: warning: unused parameter 'arg' [-Wunused-parameter]
 int async_run(void (*task)(void *), void *arg) { return -1; }
                                           ^
src/libsock.c: In function 'sock_max_capacity':
src/libsock.c:149:12: warning: comparison between signed and unsigned integer expressions [-Wsign-compare]
   if (flim < rlim.rlim_cur)
            ^
src/libsock.c: In function 'sock_lib_init':
src/libsock.c:302:5: warning: missing initializer for field 'offset' of 'struct <anonymous>' [-Wmissing-field-initializers]
     };
     ^
In file included from src/libsock.c:11:0:
src/libsock.h:364:11: note: 'offset' declared here
     off_t offset;
           ^
src/libsock.c: In function 'sock_flush_os_sendfile':
src/libsock.c:353:3: warning: comparison of unsigned expression < 0 is always false [-Wtype-limits]
   if (sent < 0) {
   ^
make: *** [tmp/src/libsock.o] Error 1
```

**Comment by boazsegev** [comment]
Hi,

Thanks for letting me know.

From what I understand (I just woke up, so maybe I missed something), it's a collision between the system include files (i.e. `/usr/include/bits/stat.h`) and a fix I wrote for compiler differences between clang and GCC-4 on Ubuntu 14 LTS (the "trusty" release used on Heroku).

What compiler are you using?

The code that your compiler is complaining about appears 14 times in the code, it looks like this:

```c
#ifndef __unused
#define __unused __attribute__((unused))
#endif
```

I replaced all the time this code appears with:

```c
#ifndef UNUSED_FUNC
#define UNUSED_FUNC __attribute__((unused))
#endif
```

It should compile correctly when using clang or gcc.

Please update the library from this branch and test again (be careful not to loose changes you want to keep).

**Comment by recoilme** [comment]
Hi! Brilliant work!
I test default demo.c (gcc, compile like a sharm) with ab on debian server with 20 cores (ab -n 1000000 -c 200 -k http://127.0.0.1:3000/)
Memory about 34kb and dont grow from test to test (free after test finished)
And very promised results with 5 microseconds on request
I think its perfect! Keep your good work up, please
```
ab -n 1000000 -c 200 -k http://127.0.0.1:3000/
This is ApacheBench, Version 2.3 <$Revision: 1604373 $>
Copyright 1996 Adam Twiss, Zeus Technology Ltd, http://www.zeustech.net/
Licensed to The Apache Software Foundation, http://www.apache.org/

Benchmarking 127.0.0.1 (be patient)
Completed 100000 requests
Completed 200000 requests
Completed 300000 requests
Completed 400000 requests
Completed 500000 requests
Completed 600000 requests
Completed 700000 requests
Completed 800000 requests
Completed 900000 requests
Completed 1000000 requests
Finished 1000000 requests


Server Software:
Server Hostname:        127.0.0.1
Server Port:            3000

Document Path:          /
Document Length:        41 bytes

Concurrency Level:      200
Time taken for tests:   5.389 seconds
Complete requests:      1000000
Failed requests:        0
Keep-Alive requests:    1000000
Total transferred:      205000000 bytes
HTML transferred:       41000000 bytes
Requests per second:    185572.41 [#/sec] (mean)
Time per request:       1.078 [ms] (mean)
Time per request:       0.005 [ms] (mean, across all concurrent requests)
Transfer rate:          37150.73 [Kbytes/sec] received

Connection Times (ms)
              min  mean[+/-sd] median   max
Connect:        0    0   0.1      0       5
Processing:     0    1   0.3      1       3
Waiting:        0    1   0.3      1       3
Total:          0    1   0.3      1       7

Percentage of the requests served within a certain time (ms)
  50%      1
  66%      1
  75%      1
  80%      1
  90%      1
  95%      2
  98%      2
  99%      2
 100%      7 (longest request)
```

**Comment by boazsegev** [comment]
Hi,

Thanks for the keeping me posted and for sharing the benchmark data :-)

I'm not sure you're interested in this information (and maybe you already know this), but you can edit the `server_run` function to fork the server across processes, allowing you to use more of the cores.

Instead of using the `HTTP_SHOOTOUT_TEST` macro inside `main`, you can use:

```c
#undef THREAD_COUNT // just in case
#define THREAD_COUNT 1 // depending on your use-case, you might want more threads.

#undef PROCESS_COUNT // just in case
#define PROCESS_COUNT 19 // leave one core for the kernel and the ab test tool

int main(void) {
  if (http1_listen("3000", NULL, .on_request = http1_websocket_shotout,        
                   .log_static = 1))                                           
    perror("Couldn't initiate HTTP service"), exit(1);                         
  server_run(.threads = THREAD_COUNT, .processes = PROCESS_COUNT);
}
```

On a 20 core machine you might see better results... Or you might hit the `ab` testing tool limit, who knows...

**Comment by recoilme** [comment]
Thank you!
May you give advice with params will be optimal if we want to serve around 3000 clients from 10 frontends? I am dont understand thread/process - process - it's fork or what?

Right now we have thin wraper to sophia.systems db writhed in Nim: https://github.com/recoilme/pudge with memcached protocol
But it serve only around 20000 connections per second with 5 ms response time Because it only multi process, not async 

I look at libevent and create some simple server on it (based on examples from internet) - https://github.com/recoilme/libevsrv - it scale more good - but your server looks more complex and simple. May you please explain how it scale/work? It async and multithreaded as i see from tests, right? Is it stable for production?

**Comment by boazsegev** [comment]
Hi @recoilme ,

I'm a little short on time today, so please forgive me if my explanation is short.

**Production ready?**

I don't know...

The Ruby server Iodine is implemented using this library and it's being used in production (I use it as well as others). Iodine performs better than most servers I used in production so far and I think this is a good sign.

On the other hand, both HTTP and Websockets are very common, so they got better testing.

If you are writing your own protocol, you might run into things that I didn't test well enough. If this happens, I'm happy to fix things up.

This library is designed for Linux / BSD systems. It was tested on Ubuntu, macOS and FreeBSD... but there are many Linux and BSD variations and I'm not sure how well it will compile or perform on all of them. 

However, **this GitHub repo branch isn't stable, it's a development branch**.

For a stable environment, you need to fork the branch into your project (or simply copy the source code files). 

If you aren't using HTTP or Websocket, I don't think you will need to copy the source files in the `http` folder or the `bscrypt` library.

**Scaling**

Facil.io uses an evened design from the core up. Facil.io's evented design supports both multi-threading and multi-process horizontal scaling. It also uses a non-blocking socket abstraction that offers (in addition to being non-blocking) extra security and a user-land buffer.

The event loop is used for all events using the code in `libasync`. The event loop can be multi-threaded (optionally) but there can be only one event loop per process.

[The server reactor](https://github.com/boazsegev/facil.io/blob/5ff6ac56a648e9fd0278eb0e3d6845184444c7d7/src/libserver.c#L415-L473) is just an event. The server reactor will schedule all the server events and than it will (re)schedule itself, so that it "loops" as an event instead of a loop.

The server reactor is set up by default to ["skip" loops](https://github.com/boazsegev/facil.io/blob/5ff6ac56a648e9fd0278eb0e3d6845184444c7d7/src/libserver.c#L450-L455) when there are more events to handle, so active requests get priority over waiting connections or slow clients.

This allows better process scaling, since `accept` is only called when there aren't any pending events for existing requests. This makes it easy for the OS to manage load balancing using the shared listening socket(s).

**Choosing the best Settings** (This is a big question)

3000 clients should be easy for a single process... I tested a single core Linux server serving 20K clients at a time before `ab` failed on me (I think `ab` is limited to 20K). Did you test against 20K connections?

`ab -n 1000000 -c 20000 -k http://127.0.0.1:3000/`

BUT 3-30K req. per/sec might be difficult, depending on how complicated and heavy each request might be.

30,000 clients all making a request at the same time should complete fairly fast. But if the requests are all heavy, more concurrency will be required. Also, you might consider implementing a memory pool for the connection objects (since `malloc` and `free` can be expensive).

The [`processes` option](https://github.com/boazsegev/facil.io/blob/5ff6ac56a648e9fd0278eb0e3d6845184444c7d7/src/libserver.h#L270-L272) uses [`fork` under the hood](https://github.com/boazsegev/facil.io/blob/5ff6ac56a648e9fd0278eb0e3d6845184444c7d7/src/libserver.c#L537-L545).

I'm pretty sure the sophia.systems db is thread safe (you can access the data from a multi-threaded server), and I think it's [mmap mode](http://sophia.systems/v2.2/admin/mmap.html) is safe for multi-process access... but I'm not sure.

Another thing to consider is the way you handle the server-side code.

Will you write evented code, using [`server_task`](https://github.com/boazsegev/facil.io/blob/5ff6ac56a648e9fd0278eb0e3d6845184444c7d7/src/libserver.h#L450-L463) , [`async_run`](https://github.com/boazsegev/facil.io/blob/5ff6ac56a648e9fd0278eb0e3d6845184444c7d7/src/libasync.h#L95-L109)?  (if you use the zero-copy HTTP/1.1 protocol provided with facil.io, you will need to remember to copy the HTTP/1.1 request before scheduling any events).

Will you communicate with the sophia.systems db using callbacks?

All these, as well as hardware variations (number of cores, number of CPU threads), effect the settings you will choose for `.threads` and `.processes`.

The more your code is evented, the less important it is to have concurrency "redundancy". But, if your code is less evented, or uses some "blocking" calls, you might want to have more concurrency than you need, just to make sure that even if the server is busy, it's still responsive.

The highest performance guideline is to have as many processes / threads as the number of cores (if to be specific, you might want to have as many processes as you have cores and as many threads per process as you have CPU threads pre core)...

... but doing this is often a mistake, because the server might become unresponsive when some clients make very CPU intensive requests (i.e. blocking database transactions etc').

For a Ruby server I'm using 16 threads * the number of cores. The server isn't blocking on databases calls, but if I had a blocking database, I would probably use 32 threads. This way, if some requests are "heavy" for the CPU, the extra threads (at the price of context switches) still make sure that the server is responsive.

Extra threads create extra context switches, which can hurt performance, but it improves responsiveness.

**Comment by recoilme** [comment]
Thank you Boaz for detailed answer!
I will look forward and think how to implement protocol better. May be it will be not memcached protocol but http or websockets because some things not trivial with async clients. Right now i am not sure. Sophia is blocking database but thread safe.

**Comment by boazsegev** [comment]
Hi,

You're very welcome.

I thank you for bringing this feature to my attention.

You are right in pointing out that facil.io doesn't have an integrated `MSG_PEEK` feature.

However, please consider these few points.

1. [Even if `MSG_PEEK` succeeds, the next `recv` call might fail or return partial data](http://stackoverflow.com/questions/864731/if-a-nonblocking-recv-with-msg-peek-succeeds-will-a-subsequent-recv-without-msg), mostly due to possible signal interruption in the kernel layer and possible socket layer changes (i.e. disconnections).

      This is only a small risk, but it does effect the security of the application.

2. Using SSL with `MSG_PEEK` is very different and practically impossible to get right.

     Facil.io doesn't provide or an SSL library at the moment, but it's quite easy to set one up by using the [`sock_rw_hook_set` function](https://github.com/boazsegev/facil.io/blob/5ff6ac56a648e9fd0278eb0e3d6845184444c7d7/src/libsock.h#L463-L471)... However, if you tie the protocol to this lower-level feature (`MSG_PEEK`) , it might be hard to implement SSL when you decide to do so.

3. I think `MSG_PEEK` will be easy to implement (but not safe and not event-friendly) by using the `fd` instead of the connection's `uuid`, with the [`sock_uuid2fd` macro](https://github.com/boazsegev/facil.io/blob/5ff6ac56a648e9fd0278eb0e3d6845184444c7d7/src/libsock.h#L72)...

     I also think that implementing a receive buffer is much easier, safer and more flexible than you might suspect.

     In addition, implementing a receive buffer allows you to prevent malformed request attacks and optimize resource usage.

     Writing the HTTP and Websocket protocols helped me to realize how important it was for the stability and security of the server.

     For example, by using a temporary buffer, HTTP was able to move large POST requests to a temporary file, so you can upload Gigabytes of data without abusing the RAM. This might also be true for memcached requests that might have very long keys or values in base64 encoding.

     As another example, by using a temporary buffer, Websockets was able to set a security limit for incoming message sizes and close an abusive connection before having to read (or parse) the actual message. This might be important for your server too, to prevent attacks on the server.

4. Using HTTP or even Websockets will add an overhead to both the client and the server as well as some security restrictions that might not be the same as what you want. This isn't always bad, because you get other stuff in return (better NAT handling and an extra security layer), but it's not always what you want either.

I'm not sure if you considered these issues before or if security was a concern, but I hope my answer gave you some ideas about how you might want to approach the protocol.
