### ISSUE TITLE
Build issue

### ISSUE THREAD

**Issue by Taymindis** [boazsegev/facil.io#31]
I can't build via make /usr/bin/ld: cannot find /usr/lib64/libasan.so.0.0.0

**Comment by boazsegev** [comment]
@Taymindis ,

Thank you for opening this issue.

Can you please give me more information so I can try to replicate the issue?

What OS / version you using?

Which compiler / version?

What facil.io version (this information is located in the facil.h file)?

What `make` command are you using?

I am guessing that this might be related to the address sanitizer on your system, (but it's only used in the DEBUG mode, so I'm not sure it's really effecting you)...

...Try editing the `OPTIMIZATION` flags in the `makefile`, removing the `-fsanitize=address` flag from the list.

**Comment by Taymindis** [comment]
The OS : NAME="Red Hat Enterprise Linux Server", VERSION="7.2 (Maipo)"
Compiler : gcc version 4.8.5 20150623 (Red Hat 4.8.5-16) (GCC)
Facil : 
#define H_FACIL_H
#define FACIL_VERSION_MAJOR 0
#define FACIL_VERSION_MINOR 6
#define FACIL_VERSION_PATCH 4

I've tried your suggestion, it came out with another error:-
/usr/lib/gcc/x86_64-redhat-linux/4.8.5/../../../../lib64/crt1.o: In function `_start':
(.text+0x20): undefined reference to `main'


I tried using your cmake build, it is working fine, but you didn't do install build. It makes me confuse when I want to use the library, all header need to organize.

**Comment by boazsegev** [comment]
@Taymindis , thanks for the details.

The CMake build variation is used as a CMake source library (it ignores any source files in the `src` folder and was intended to be included from another project's CMakeLists.txt file. This is why the linker is complaining about the missing `main` function when using CMake.

I'm currently traveling and can't test the (Red Hat 4.8.5-16) (GCC) environment. However, I suspect this might be a compiler version issue.

The oldest compiler I used for testing was the GCC 4.9 version. I haven't used it in a while but it should work since it supports C11. Note that GCC version 8.1 is available (though I still use the 6.x versions).

Is there any chance that you try using an updated compiler, or is it critical that facil.io support the 4.8.5 version?

**Comment by Taymindis** [comment]
Hi ,

So far my Redhat gcc compiler version is up to 4.8.5 only.
I have to manual install another gcc to overwrite this version, but it’s
not allowed to do that.

Anyway, I will try to build with cmake and install  the facil headers and
the facil static library . Is that all I needed right?

**Comment by boazsegev** [comment]
@Taymindis 

> Anyway, I will try to build with cmake and install  the facil headers and the facil static library . Is that all I needed right?

I think I better understand the error.

I think the error is that you expect to install the library on your machine and the facil.io wasn't meant to be installed as a library. 

The normal procedure is to compile the facil.io code directly with your application. Each application will carry an independent copy of all the facil.io code, which might be wasteful for some systems (but is usually simpler to handle when using `docker` or similar sandboxing tools).

To build an application it's normal to [run (or follow) the script](https://github.com/boazsegev/facil.io/blob/c5c740d3a0ca5dc7813a9704c4eed29d3c3c6875/scripts/new/app) using this command:

     bash <(curl -s https://raw.githubusercontent.com/boazsegev/facil.io/master/scripts/new/app) appname

Than add / edit the code in the `./src` folder and write your application.

If you really want to use facil.io as a static / dynamic library, you can do so. Either edit the makefile or follow these instructions:

1. Run `make libdump` to dump all the include files into the `libdump/include` folder (it will be created).

2. Run `make lib` to compile the library into the `tmp/libfacil.so` file.

3. Move the library file and the include files to the appropriate folders (depending on your organization).

**Comment by Taymindis** [comment]
@boazsegev 

It is working now! But all of your headers file is specific with double quote "xx.h". So i need to build with gcc -I/usr/local/include/facil echo.c -std=c11 -lfacil -oecho

Why can't you just give a simple cmake to install your library and header so that We can integrate your library with other tools

**Comment by boazsegev** [comment]
@Taymindis , I would be happy to help, but I might need your help understanding your request.

I don't use CMake, but I thought that it's possible to [use the facil.io as a CMake submodule](https://github.com/boazsegev/facil.io#using-facilio-as-a-cmake-submodule). Is that what you mean?

I don't think the use of `#include "foo.h"` vs. `#include <foo.h>` will help, because using quotes (the first variation) will work also for system include folders.

Is there a different CMake approach that will add the the facil.io include files to the system's include path?
