### ISSUE TITLE
Logo Proposal for Facil.io

### ISSUE THREAD

**Issue by area55git** [boazsegev/facil.io#33]
Hi @boazsegev, I'm a graphic designer and I like to collaborate with open source projects. Do you know that the graphic image of a project is very important? thinking about it I would like to design a logo for your Project Facil.io.

I will be pleased to collaborate with you.
Att
Francisco

**Comment by boazsegev** [comment]
Hi @area55git (Francisco?) ,

Thank you for contacting me 🙏🏻

I would love to have a nice logo for the project, What did you have in mind?

Kindly,
   Bo.

**Comment by area55git** [comment]
Bo, Do you have a color suggestion or an idea? to start designing some sketches

**Comment by boazsegev** [comment]
I don't really have much experience making logos.

There are 2 different color schemes to the [facil.io website](http://facil.io) (day and night). Maybe they could provide a start? I like the night theme a little better.

I think it should be something simple but fun (colorful), with reds and blues or gray, maybe an almost organic look.

Similar network libraries include [duda.io](http://duda.io/), [libuv](https://libuv.org), [libev](http://software.schmorp.de/pkg/libev.html), [redis.io](https://redis.io) and [nginx](https://www.nginx.com)... they are all different than facil.io, but have some similarities as well.

My personal favorite so far (from another project I have), is the handwritten logo for [plezi.io](http://www.plezi.io), which actually uses facil.io under the hood.

Maybe they are good sources of inspiration?

B.

**Comment by area55git** [comment]
Very complete your explanation, in a few days I will have several proposals, I hope to do a good job and you like some.

**Comment by boazsegev** [comment]
@area55git ,

Thank you for your offer. I was looking forwards to seeing your work :-)

...but I'm assuming you found yourself busy with other stuff?

It's all good. We can close the issue if you decided not to move forward with this. Again, thanks and no worries, just let me know.

Kindly,
Bo.

**Comment by area55git** [comment]
Hi, Bo. sorry for the delay, I was really busy, but tomorrow I start with your sketches, today I'm finishing another contribution. please do not close this issues.

**Comment by boazsegev** [comment]
Oh, wow, that's great news :-) Sure, I'll keep the issue open 👍🏻

**Comment by area55git** [comment]
Hi @boazsegev According to the indications after reviewing the suggestions, these are the sketches

[![LOGO_PROPOSAL_FOR_FACIL.jpg](https://s33.postimg.cc/55wnw83pr/LOGO_PROPOSAL_FOR_FACIL.jpg)](https://postimg.cc/image/6xpmr4n2j/)

The option # 1 and # 2 are made up of 3 overlapping rectangles that form the letter "F" and in option # 3 the letter "F" is formed with circles, some joined that give the feeling of fluidity (movement).

I hope you like it...

Remember that they are sketches, you can suggest any change, the idea is that you are happy with your logo.

**Comment by area55git** [comment]
These options can be adapted for day and night

**Comment by boazsegev** [comment]
Hi, wow, great work 👍🏻

Sorry for the delay - finals are coming up and I'm caught in the whirlwind.

I loved the options and the general approach, placing the name under the logo rather than inside the logo - I think that's great.

I also love the blobby handwritten version... I love how personal and non-technical it feels.

I strive to make "facil.io" fun for developers and I really feel that option number 1 gives that vibe. Nice 👍🏻

However...

I find the hand-written font hard to read.

Also, I feel that the letter "F" in the logo isn't obvious enough, at least not for me... I had to read the description before I noticed the letter.

Also, I wonder if a single letter is the best choice... How about "fio" - this would match some of the function names and prefixes and actually completes the initials for the library ("**f**acil **i**nput **o**utput", or "fio" for short).

Can we put _fio_ in the center of the logo, or is it too much?

Kindly,
  B.

**Comment by area55git** [comment]
Hi @boazsegev What do you think of these proposals?

[![LOGO_PROPOSAL_FOR_FACIL.jpg](https://s33.postimg.cc/r0qgoqc27/LOGO_PROPOSAL_FOR_FACIL.jpg)](https://postimg.cc/image/jkr72xocr/)

**Comment by boazsegev** [comment]
Hi @area55git,

Wow, that was fast. Thanks!

I love the `fio` on option # 1 (left most).I also love the font on option # 1 (at the bottom). It's rounded and inviting.

I also love the other two options. The arrow through the F is cool and the Hexagon is super... but I think focusing on variations on option # 1 would be ideal.

Is it okay if we did another round?

I would love to see option # 1 with a lower-case "f" and a softer division between the "f" and the "io"... maybe a altering the blobs a bit, making them share a point of origin (the bottom of the "f")...?

I am very thankful and don't want to push. I would also love to read your opinions.

Kindly,
   Bo.

**Comment by benjcal** [comment]
I couldn't help my self to comment. I loved #2! The hexagons, colors and wide light font give to it a feel of modern and performance.

#1 in my opinion seems a little too playful, something that I'd assisted with an indie games from the play store. I'm not sure if it's because of the colors. Maybe it also had to do with the fact that a lot of app icons are just the first letter of the name of the app.

Also, hello @boazsegev!! Took me a little bit of time but I'm excited to contribute again! (I'm still thinking about a router, packing this as a lib for homebrew/macports/rpm/deb :-)

Anyway, thanks a lot @area55git! Looking forward to see what you come up next :-) 

Hopefully from the logo we can get a color scheme and make facil.io even nicer! (after all, I'm webdev during the day :)

**Comment by area55git** [comment]
Hi @benjcal Taking your suggestions from # 2

![logo proposal for facil 2](https://user-images.githubusercontent.com/38330420/43843644-043cbdae-9af6-11e8-9ef7-8f055d05ff40.jpg)

**Comment by benjcal** [comment]
@area55git you are awesome!! The new version of # 1 looks awesome, the new fonts change a lot of how it felt and looks a lot more professional. Also after reading through the code quite a while I can see the why behind "fio"

About # 2, the first three look fantastic too me particularly the blue one and the first monochromatic.

But then again it's @boazsegev who has the last word on this! 

Thanks again!

**Comment by boazsegev** [comment]
Hi @benjcal , thank you for joining the discussion and thank you for your input.

@area55git , I know you love them all, but do you have a favorite or two?

@benjcal , I was about to ask for your favorite when you posted your message... so I guess the ones you like best are option # 2 in blue and monochrome...? Or do you have favorites also among option  # 1?

Since it's the three of us, I would love to read your opinions and take them into account.

**Comment by area55git** [comment]
If you want something a little informal I recommend the # 1 in blue

If you want something more technological or formal the # 2 in blue

**Comment by area55git** [comment]
According to the description on your profile, I would recommend using the logo # 1

**Comment by benjcal** [comment]
@boazsegev that's a hard question. I agree with @area55git that # 1 is more informal and # 2 looks more techie. Thinking that our audience are developers somehow # 2 seems more trustworthy and reliable.

Among # 1 the blue and first mono are my two favorites, the have a more relax feel to them, and when I was using CouchDB with their clear theme _"Apache CouchDB has started. Time to relax."_ I can also appreciate the value in # 1.

About the colored # 1, would it be possible to have a little more padding between the top of the 'f' and the top of the logo? similar to the same space in the monochromatic one.

**Comment by boazsegev** [comment]
@area55git  - thank you for the amazing options, your time, your kindness and your skill.

@benjcal - thank you for your input.

This discussion is what open source is all about and I'm happy for the input, so thank you both again, @area55git  and @benjcal  .

The biggest feedback I'm reading between the lines is that facil.io could be better served with a more mature image (this includes the documentation approach as well, though not the core foundation based on "ease of use") - am I understanding correctly? Do you think option # 2 will serve us better?

Kindly,
B.

P.S.

I had one last (crazy) idea, which is to replace the blobs in # 1 with the hexagon from # 2, but keep the soft fonts on the "fio" and "facil.io"... but I guess I asked for too many iterations as is and maybe I just never wanted to grow up...

**Comment by area55git** [comment]
![logo proposal for facil 3](https://user-images.githubusercontent.com/38330420/43845986-42832d32-9afb-11e8-9b00-1f625d3fed7e.jpg)


or


![logo proposal for facil 4](https://user-images.githubusercontent.com/38330420/43845993-484be0ec-9afb-11e8-82d2-7c35769631af.jpg)

**Comment by area55git** [comment]
I definitely like # 2
If you plan to use it as an icon or favicon this is the best option

**Comment by boazsegev** [comment]
I guess by majority vote, option # 2 it is :-)

Thank you!

**Comment by benjcal** [comment]
oh wow, in that context # 2 looks beautiful! 🤩

and in a context like devdocs.io I feel like it will pop more!
<img width="229" alt="screen shot 2018-08-08 at 11 14 14 am" src="https://user-images.githubusercontent.com/2781653/43846418-4f12eda2-9afc-11e8-9f5a-759da74a20fb.png">

**Comment by boazsegev** [comment]
Cool, let the integration begin 🎉

@area55git - thank you so much!

How do we continue from here?

**Comment by area55git** [comment]
I would like to make a proposal replacing the bubbles and placing the hexagon

**Comment by benjcal** [comment]
on that same line of thought, I was trying to find the repo for the facil.io website but couldn't find it.

I think we could use a repo to host the site with a static site generator like hugo or jekyll and use a travis CI to automate the builds of such site

@area55git maybe we can use a svg version of the logo and a couple of pngs (@2x, @3x...) for page logo

**Comment by boazsegev** [comment]
@area55git - sure, let's try it.

**Comment by area55git** [comment]
Perfect, I will prepare the final files in various formats (SVG, PNG, EPS) and in different sizes, I would like you to place the logo in the Readme folder to make a PR to merge?

I will send you a link on GoogleDrive with all the logos

**Comment by benjcal** [comment]
@boazsegev and how's the process to build it and deploy it? is it manual?

I think that we can have them separated. In the docs folder we can have text or srt (similar to the linux kernel docs) and soon info and man page files. The site can be a separate repo or separate branch. What is needed is a repo/branch with the build files on the root and a branch where Travis CI would deploy the build index.html file

**Comment by benjcal** [comment]
@boazsegev I think this approach frees us to have a more involved site and, thinking about the logos, an assets folder to place them while keeping the repo of the library itself relatively clean

**Comment by benjcal** [comment]
I can work later today with the skeleton of such build system and see how we like it

**Comment by benjcal** [comment]
about the google drive link @area55git, we wouldn't want to use your personal storage space. If @boazsegev is ok with this I think a PR would work just fine. We might later move them to keep separation of concerns but for now it should be ok.

**Comment by area55git** [comment]
I'm new to github and I'm not a developer, so I give them the link (just design logos🤩🤩🤩), you can create a folder in the repository to host the logos there.

**Comment by benjcal** [comment]
😃No prob. Do write on your resume your contribution to an open source project!

**Comment by boazsegev** [comment]
@area55git - Do what's easiest for you. A PR would be great since it would also go on record to show your contribution, which I would love people to see. But it's your choice.

@benjcal  - The build process is automated. Whenever an update is pushed to the master branch, the website is rebuilt. Sure, we can move the documentation to a different branch / repo, but I find it comfortable to manage a single release record (using git tags) which also manages the related documentation cycle.

**Comment by benjcal** [comment]
Didn't looked at the tags 😂

**Comment by benjcal** [comment]
@boazsegev would you agree though about having a separated branch for the site or would you consider, for example, a website with the new logo a new release of facil? what adding or updating documentation, new release to?

**Comment by area55git** [comment]
![logo proposal for facil](https://user-images.githubusercontent.com/38330420/43859584-0a85f486-9b1f-11e8-95d5-e16307bb1662.jpg)

**Comment by benjcal** [comment]
🤩🤩🤩🤩

**Comment by area55git** [comment]
I'm not sure about the monochromatic version

It may be so

![logo proposal for facil 2](https://user-images.githubusercontent.com/38330420/43859995-520c1f3c-9b20-11e8-9384-3ba3a585ee67.jpg)

**Comment by boazsegev** [comment]
@area55git 🤩👏🏻👏🏻👏🏻

I love both the versions with text under the logo and the versions with the text next to the logo.

I love the additional border on the stand alone icon-logos (great for fav icons) 👏🏻👍🏻 though I also love the borderless connectivity of the logo when there's text attached.

As for monochrome versions, I think both approaches look great. I'm a bit more inclined towards the simpler versions (the second iteration)... but at the end of the day, I'll trust your taste and use the version you decide on.

As a side note, I much prefer to have the website display the color version (though I will probably set it up to print the monochrome version when printing the website).

B.

**Comment by boazsegev** [comment]
@benjcal ,

I don't mind placing the website on a separate branch or repo, I just don't see the added value. What can we do with a branch that we can't do using a `fork` and a `merge`...?

As for versioning - the version scheme follows [semantic versioning](https://semver.org/spec/v2.0.0.html) with the caveat that I plan to use development versioning until TLS/SSL and possibly HTTP/2 are implemented.

This means that changes to the last digit (0.0.1 -> 0.0.2) indicate both patch versions and added features (which is usually the middle number). The key requirement is that the API remains unaltered and existing code behaves the same.

I don't think documentation updates should effect the version. When the documentation is updated, the developer experience is improved in ways that aren't related to the library's code. This would include spelling corrections, added information, styling, design etc'.

Of course, the website should reflect the latest release as far as content goes... which means that the master branch shouldn't be the development branch... even though it currently is, which is a temporary misstep I allowed myself and shouldn't have.

B.

**Comment by benjcal** [comment]
@boazsegev ,

the idea behind a separate branch is just a separation of concerns but after thinking more about it is not completely necessary. For some reason I've been thinking that the use of the library would clone the repo in order to use the library but judging from the script that's not the case, since there's a separate release archive and I assume that the CMake submodule doesn't downloads the docs folder either.

I was looking at a couple of options to manage the documentation in an easier way than manually making a theme with the new logo and such and a couple of the ones I found the easiest where gitbook.com and readthedocs.org. We can also decide on a theme that matches the logo or even make one for Jekyll. From those Gitbook seems the easiest and it looks very nice and easy to navigate. Next is Jekyll even though it might be a little more involved. If I dare to call upon @area55git for a simple website layout 😅. I'm pretty good at implementing an sketch in HTML but not very good at designing it.

We could make a new issue to talk more specifically about facil.io, the looks and goals of it

**Comment by area55git** [comment]
### [FILE DOWNLOAD](https://drive.google.com/open?id=1ganLyE1faXr73MsTMhZn7cdooNWjmTLm)

![derechos](https://user-images.githubusercontent.com/38330420/43867679-3748e6ea-9b38-11e8-8855-55b0b7f35c43.jpg)
This work is licensed under a [Creative Commons Attribution 4.0 International License.](https://creativecommons.org/licenses/by/4.0/)

**Comment by area55git** [comment]
PR #34

**Comment by boazsegev** [comment]
@benjcal  - I'm on vacation for 20 days or so, but I'll try to stay in touch.

Let's open a new issue and discuss this there.

**Comment by boazsegev** [comment]
I updated the logo to make the design responsive (changing screen and window sizes) 🎉

We have the logo in the readme, but not yet on the website (which probably needs a new color scheme and all).

Thank again 🙏🏻👍🏻

**Comment by boazsegev** [comment]
I take it back... GitHub strips styles (CSS) from markdown, preventing us for implementing a responsive design.

Thoughts and ideas would be appreciated (though perhaps on a new thread).

**Comment by area55git** [comment]
@boazsegev It's a shame not to be able to place the background in a responsive way, anyway the logo in the readme folder looks great. Thank you very much for allowing me to collaborate in your project and very grateful ambien with @benjcal  for your valuable contribution. If you need a logo for another repository please do not hesitate to let me know that I will gladly collaborate.

**Comment by benjcal** [comment]
@area55git thanks so much!! I'm very thankful you your contribution and I'm so looking forward to use it in a more marketable homeoage for this project 😁

I actually do have another repo but I'm not in the stage of working with the logo as much as I am of making a complete code rewrite or even change of framework 😂😅😢😭

But thanks, I really appreciate the offer and hopefully will take advantage of it!

**Comment by boazsegev** [comment]
I just published the new Website.

I love the way the new logo looks and the new design (especially the night mode theme).

In the future I want to polish the design even more, especially the home page, making it more welcoming (and probably using a big horizontal version of the logo).

This was the milestone marking the time to close this issue.

Thank you both for your input and help and thank you @area55git for the logo 🙏🏻👏🏻🎉👍🏻
