### ISSUE TITLE
Strange with keep-alive

### ISSUE THREAD

**Issue by recoilme** [boazsegev/facil.io#4]
Hi, Boaz!
It's again i)
At first off all, i create database  prototype based on your library: https://github.com/recoilme/okdb

But some strange things found with flag keep alive(
Then i test with keep-alive - all looks good:
ab -n 1000 -c 200 -k http://127.0.0.1:8888/
Requests per second:    86452

But if i disable keep-alive:
ab -n 1000 -c 200 http://127.0.0.1:8888/
Requests per second:    33.85

I test in on mac and debian with same results.

May be i do something wrong with headers? https://github.com/recoilme/okdb/blob/master/okdb.c (sophia not used for this request)

And i dont may reproduce right now - but i see one time, then i send long value (around 1024 bytes) without keep-alive from curl it dont work

Example request:
```
curl -v -H "Connection: keep-alive" -X PUT -d "01234567890123456789012345678901234567890123456789012345678901234567890123456901234567890123456789012345678901234567890123456789012345678901234567890123456789012345678901234567890123456789012345678901234567890123456789012345678901234567890123456789012345678901234567890123456789012345678901234567890123456789012345678901234567890123456789012345678901234567890123456789012345678901234567890123456789012345678901234567890123456789012345678901234567890123456789012345678901234567890123456789012345678901234567890123456789012345678901234567890123456789012345678901234567890123456789012345678901234567890123456789012345678901234567890123456789012345678901234567890123456789012345678901234567890123456789012345678901234567890123456789012345678901234567890123456789012345678901234567890123456789012345678901234567890123456789012345678901234567890123456789012345678901234567890123456701234567890123456789012345678901234567890123456789012345678901234567890123456789012345678901234567890123456789012345678901234567890123456789012" http://127.0.0.1:8888/hello
* Hostname was NOT found in DNS cache
*   Trying 127.0.0.1...
* Connected to 127.0.0.1 (127.0.0.1) port 8888 (#0)
> PUT /hello HTTP/1.1
> User-Agent: curl/7.38.0
> Host: 127.0.0.1:8888
> Accept: */*
> Connection: keep-alive
> Content-Length: 1021
> Content-Type: application/x-www-form-urlencoded
>
* upload completely sent off: 1021 out of 1021 bytes
< HTTP/1.1 200 OK
< Content-Length: 2
< Connection: keep-alive
< Keep-Alive: 1;timeout=5
<
* Connection #0 to host 127.0.0.1 left intact
```

And last - then i try to reproduce - looks like server down:
```
./tmp/okdb

Initialized libsock for 512000 sockets, each one requires 32 bytes.
overall ovearhead: 16384000 bytes.
Initialized packet pool for 1024 elements, each one 16424 bytes.
overall buffer ovearhead: 16818176 bytes.
=== Total: 33202176 bytes ===

* Listenning on port 8888
* Running 19 processes X 1 threads.
* [23163] Running.
* [23164] Running.
* [23161] Running.
* [23162] Running.
* [23165] Running.
* [23166] Running.
* [23167] Running.
* [23168] Running.
* [23169] Running.
* [23175] Running.
* [23177] Running.
* [23179] Running.
* [23181] Running.
* [23183] Running.
* [23185] Running.
* [23187] Running.
* [23154] Running.
* [23189] Running.
* [23191] Running.
Segmentation fault
```
But then i grep - i see some running procces and server proccesed request.
```
ps aux|grep okdb
vkuliba+ 23161  0.1  0.0 3591948 33572 pts/0   Sl   14:08   0:15 ./tmp/okdb
vkuliba+ 23164  0.1  0.0 3591948 33572 pts/0   Sl   14:08   0:16 ./tmp/okdb
vkuliba+ 23165  0.1  0.0 3591948 33572 pts/0   Sl   14:08   0:17 ./tmp/okdb
vkuliba+ 23167  0.1  0.0 3591948 33572 pts/0   Sl   14:08   0:15 ./tmp/okdb
vkuliba+ 23168  0.1  0.0 3591948 33572 pts/0   Sl   14:08   0:16 ./tmp/okdb
vkuliba+ 23175  0.1  0.0 3591948 33572 pts/0   Sl   14:08   0:16 ./tmp/okdb
vkuliba+ 24072  0.0  0.0  14644  1612 pts/0    S+   16:43   0:00 grep okdb
```

**Comment by recoilme** [comment]
Segfault - my mistake, iIdon't check  on null body_string

**Comment by boazsegev** [comment]
I'm a bit busy today, I'll try to be short and fast, if I don't answer everything, I'll write more when I can.

I think you encountered a known issue with the HTTP protocol that was probably (maybe) made worst because your previous code was writing directly to the sockets instead of using an `http_response_s` object (this object will optimize parts of the response and make sure it's formatted correctly).

One of the issues in the HTTP/1.1 protocol is that it is VERY expensive to open and close network connections. There's a whole lot of processing required by the kernel as well as a TCP/IP *feature* called "slow start".

It's even worst if the same client sends a lot of requests (requiring a lot of new connections). Each client has a "cool-down" period for each connection port (about two minutes on many systems) and there's a theoretical limit on how many connection ports each client can use (~64K ports per client for each listening socket)... This is system related, not much we can do about it.

This is a serious issue if you have many requests from a single client.

In normal HTTP settings, Keep Alive should improve performance drastically.

It's also why HTTP/1.1 is being replaced with HTTP/2, why Websockets are often used instead of AJAX and why memcache was using persistent connections instead of HTTP.

The better the server is designed (the server overhead is low), the higher the performance gain for Keep Alive (the more you notice the issue with the TCP/IP layer).

For facil.io, Keep-Alive should improve performance at a X20 rate (%2000)! This is similar to nagging and it's partly because facil.io is relatively fast with a small overhead. On other systems you might see smaller improvement (they have higher overhead).

HOWEVER, I suspect some of the delays were because of the way the old code you used in the test was handling response issue.

In the old code [you wrote to the socket directly](https://github.com/recoilme/okdb/blob/cf8ab9368f4c7d6e48a9c66c2a2fab6ec0d01df2/okdb.c#L87-L96). This can cause HTTP errors in relation to the `Content-Length` header...

...When this happens, the client (`curl`) might wait for a disconnection before it realizes that the response is complete. Unless you manually close the socket, you are actually waiting for the HTTP timeout to occur (the default is 5-6 seconds).

Some of the issues you handle using `http_response_s` (i.e. [here]()https://github.com/recoilme/okdb/blob/cf8ab9368f4c7d6e48a9c66c2a2fab6ec0d01df2/okdb.c#L87-L96), but

**Comment by boazsegev** [comment]
As to the `segfault`, I'm not sure where it's coming from.

However, would you mind experimenting with me?

If you add `-DASYNC_USE_SENTINEL=1` to the CFLAGS in the `makefile` (or update the value in `libasync.c`), than the server will try to listen to [error signals](https://github.com/boazsegev/facil.io/blob/5ff6ac56a648e9fd0278eb0e3d6845184444c7d7/src/libasync.c#L302-L316)  and it will try to recuperate after some errors without crashing. It will also print an [error report with a backtrace of the stack](https://github.com/boazsegev/facil.io/blob/5ff6ac56a648e9fd0278eb0e3d6845184444c7d7/src/libasync.c#L277-L297), so you have more information about what happened.

**Comment by boazsegev** [comment]
Oh, I just noticed you know what happened... forget about it :-)

**Comment by recoilme** [comment]
Thank you Boaz!  Your code very well commended,  i will read it!

**Comment by boazsegev** [comment]
You're very welcome.

If you find that the keep-alive is slower than it should be or anything else, please let me know.

If there's anything wrong I would like to fix it. Having false alarms is better than not knowing :-)

Thank you for opening the issues.
