### ISSUE TITLE
Option to not set signal handlers

### ISSUE THREAD

**Issue by stschake** [boazsegev/facil.io#47]
Since facil is a library, it is unfortunate for it to unconditionally overwrite signal handlers with it's own. The functionality implemented through them seems non-essential and could just as well be triggered through the integrating program (e.g. fio_stop).

It should in any case chain signals to the signal handlers it overwrote, which isn't currently done.

**Comment by boazsegev** [comment]
Hi @stschake ,

Thank you for opening this issue.

You have a very fair point.

I was envisioning facil.io more as a framework, and as such allowed it some freedoms (such as ignoring the SIGPIPE instead of managing it with every call to `send`, which isn't as simple on BSD).

However, I think you are right to point out the SIGUSR1, SIGINT and SIGTERM aren't truly required and could be handled better.

I'm traveling right now, but I'll try to get to it soon.

Kindly,
   Bo.

P.S.

In the meantime, for SIGUSR1, it's possible to set the compilation flag `-DFIO_DISABLE_HOT_RESTART` and it won't be set.

**Comment by boazsegev** [comment]
Hi @stschake ,

I updated the signal handling code to propagate the signal to any pre-existing handlers (if any).

Also, it's now possible to remove the default signal handlers (and restore any previous signal handlers) using the [`fio_signal_handler_reset `](http://facil.io/0.7.x/fio#fio_signal_handler_reset) function.

For example, this could be called using the [`fio_state_callback_add ` function](http://facil.io/0.7.x/fio#fio_state_callback_add) like so:

```c
/* wrap  fio_signal_handler_reset */
static void my_reset_signals_wrapper(void *ignr_) {fio_signal_handler_reset(); (void)ignr_; }
/* inside main() */
fio_state_callback_add(FIO_CALL_PRE_START, my_reset_signals_wrapper, NULL);
```

Since the pre-start callback is called after the signal handlers were set, they will be removed.

I hope this helps...?
