### ISSUE TITLE
Processing of big test frames.

### ISSUE THREAD

**Issue by Filly** [boazsegev/facil.io#6]
Hi,
i am just testing your websocket library and noticed that when sending big text Frames like this [here,](http://pastebin.com/SnZrvxBw) the parsing Fails with "ERROR Websockets: unmasked frame, disconnecting."

Is it just for me, or can you also reproduce this on your side?

Thanks for any hints.

**Comment by boazsegev** [comment]
Hi @Filly ,

Thank you for opening this issue(!).

I'm testing and I can confirm a weakness in the parser. I'm working on a patch and I'll write the details after the patch was released.

I'm super thankful that you exposed this issue 👍

**Comment by boazsegev** [comment]
Hi @Filly ,

Thank you again for opening this issue(!).

I tried to reproduce the issue on my system and wrote a few javascript tests...

Testing with Safari and Firefox worked fine on my system (I didn't test IE, since I don't have it).

Chrome was the only browser who's Javascript engine could trigger the issue. It seems to be the only client that uses fragmentation when sending messages.

Along the way I discovered that a multi-packet message could, potentially (under certain conditions), throw the parser into an endless loop, exposing a DoS weakness (which had now been fixed).

I patched up the parser and retested on all browsers (Chrome, Safari, Firefox).

I tested with up to 2Mb size messages, which requires setting a larger `.max_msg_size` value, i.e.: `websocket_upgrade(.max_msg_size = 2097152 /* ... */)`

This now works properly on all tested browsers (I didn't test on IE).

Again, thank you for exposing the issue.

I hope you enjoy the framework. Please let me know if you run into any more issues.

Bo.
