### ISSUE TITLE
compile error

### ISSUE THREAD

**Issue by Zibri** [boazsegev/facil.io#89]
```
$ git clone https://github.com/boazsegev/facil.io
$ cd facil.io
$ make
* Detected `epoll`
* Detected `sendfile` (Linux)
* Detected 'tm_zone' field in 'struct tm'
* Detected socket API without additional libraries
* No compatible SSL/TLS library detected.
* Detected the zlib library, setting HAVE_ZLIB
* Detected Little Endian byte order.
lib/facil/cli/fio_cli.c: In function ‘fio_cli_unnamed’:
lib/facil/cli/fio_cli.c:30:28: warning: argument 2 null where non-null expected [-Wnonnull]
    (o1.data == o2.data || !memcmp(o1.data, o2.data, o1.len)))
                            ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
lib/facil/fio.h:5618:33: note: in expansion of macro ‘FIO_SET_KEY_COMPARE’
 #define FIO_SET_COMPARE(o1, o2) FIO_SET_KEY_COMPARE((o1).key, (o2).key)
                                 ^~~~~~~~~~~~~~~~~~~
lib/facil/fio.h:5874:25: note: in expansion of macro ‘FIO_SET_COMPARE’
       if (!pos->pos || (FIO_SET_COMPARE(pos->pos->obj, obj)))
                         ^~~~~~~~~~~~~~~
In file included from lib/facil/fio.h:212:0,
                 from lib/facil/cli/fio_cli.c:7:
/usr/include/string.h:63:12: note: in a call to function ‘memcmp’ declared here
 extern int memcmp (const void *__s1, const void *__s2, size_t __n)
            ^~~~~~
lib/facil/cli/fio_cli.c:30:28: warning: argument 2 null where non-null expected [-Wnonnull]
    (o1.data == o2.data || !memcmp(o1.data, o2.data, o1.len)))
                            ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
lib/facil/fio.h:5618:33: note: in expansion of macro ‘FIO_SET_KEY_COMPARE’
 #define FIO_SET_COMPARE(o1, o2) FIO_SET_KEY_COMPARE((o1).key, (o2).key)
                                 ^~~~~~~~~~~~~~~~~~~
lib/facil/fio.h:5893:27: note: in expansion of macro ‘FIO_SET_COMPARE’
         if (!pos->pos || (FIO_SET_COMPARE(pos->pos->obj, obj)))
                           ^~~~~~~~~~~~~~~
In file included from lib/facil/fio.h:212:0,
                 from lib/facil/cli/fio_cli.c:7:
/usr/include/string.h:63:12: note: in a call to function ‘memcmp’ declared here
 extern int memcmp (const void *__s1, const void *__s2, size_t __n)
            ^~~~~~
/usr/lib/gcc/x86_64-linux-gnu/7/../../../x86_64-linux-gnu/Scrt1.o: In function `_start':
(.text+0x20): undefined reference to `main'
collect2: error: ld returned 1 exit status
makefile:541: recipe for target 'build_objects' failed
make: *** [build_objects] Error 1

```

**Comment by boazsegev** [comment]
Hi @Zibri ,

Thank you for opening this issue.

I will try to answer both the error (`undefined reference to `main'`) and the warnings, and I hope this will help.

### Error: `undefined reference to `main'`

The facil.io library is a source code library. This means that facil.io expects to be imported into a new or existing application as source code.

As you know, C programs (unlike libraries) start their code execution using the `int main()` function as an entry point for the program. 

However,  when you use `git clone` there's no C program, just a library, so there's no `main` function.

To **fix** this, create a folder `./src` and add your C  program to that folder.

You can start using the boiler plate program included in the [`examples` folder](https://github.com/boazsegev/facil.io/tree/master/examples).

Alternatively, instead of using `git clone`, you can use the following command listed in the README:

```bash
 $ bash <(curl -s https://raw.githubusercontent.com/boazsegev/facil.io/master/scripts/new/app) appname
```

### Warnings: `argument 2 null where non-null expected`

This appears to be a superfluous warning.

The previous conditional in [the conditional statement](https://github.com/boazsegev/facil.io/blob/c1306722fd84a23447671619fc76eb8a11a6cb39/lib/facil/cli/fio_cli.c#L28-L30) tests the length of the string data is equal.

At this point, `NULL` could only occur if there are zero bytes to be read (which means no memory access is performed).

As a whole, the logic tests constant strings retrieved from the `main(int argc, const char **argv)` function.

These usage is assumed to be "safe" in this context where no `NULL` pointer would be forwarded by the system or the developer (there are no `NULL` pointers in the first `argc` members of the `argv` array).

In addition, NULL pointers and possible overflow are tested against beforehand (such as [here](https://github.com/boazsegev/facil.io/blob/c1306722fd84a23447671619fc76eb8a11a6cb39/lib/facil/cli/fio_cli.c#L335), [here](https://github.com/boazsegev/facil.io/blob/c1306722fd84a23447671619fc76eb8a11a6cb39/lib/facil/cli/fio_cli.c#L353) and [here](https://github.com/boazsegev/facil.io/blob/c1306722fd84a23447671619fc76eb8a11a6cb39/lib/facil/cli/fio_cli.c#L89))

---

Please let me know if this answers your concerns.

Kindly,
   Bo.

**Comment by Zibri** [comment]
thanks for the explaination!!
the funny thing is that I am not a newbie... I was just really tired and now I feel silly :D

**Comment by mucholove** [comment]
1st time user. Got the same issue! Question—(I might end up answering this on my own in the next few minutes but it is midnight...)—could it be turned into a library like `microhttpd`? — https://www.gnu.org/software/libmicrohttpd/

**Comment by boazsegev** [comment]
Theoretically you could compile facil.io as a library (using [`make lib`](https://github.com/boazsegev/facil.io/blob/beedf935200e4c0349a83d546a0b10b35d9979b4/makefile#L696)) and dump the include files into a single folder (using [`make libdump`](https://github.com/boazsegev/facil.io/blob/beedf935200e4c0349a83d546a0b10b35d9979b4/makefile#L892-L893)). At this point you'll need to manually install the library and the header files in a suitable location.

However, this isn't directly supported for two main reasons:

1. It is common to run multiple versions of the same web applications in a cluster (i.e., A/B testing, gradual deployment, API transitioning, etc'). Using facil.io as a library might break an older web application if a newer one overwrites the old library with one that isn't compatible (i.e., the upcoming transition from 0.7.x to 0.8.x versions).

2. facil.io might break ABI between versions. Although I avoid it between minor releases, facil.io is a source code library and therefor it makes no hard promises regarding the ABI.

Cheers,
   Bo.
